name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 0 点自动运行（UTC 时间）
  workflow_dispatch:       # 手动触发按钮

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/senshinya/MoonTV.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main        # 如果你的默认分支叫 master，则改成 master
          git merge upstream/main  # 如果上游默认分支叫 master，则改成 upstream/master

      - name: Push changes
        run: |
          git push origin main
